import Head from "next/head";
import { Inter } from "@next/font/google";
import PlayBar from "@/components/PlayBar/PlayBar";
import SongContainer from "@/components/SongContainer/SongContainer";
import Header from "@/components/Header/Header";
import QueueList from "@/components/QueueList/QueueList";
import styles from "./index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create digIT app</title>
        <meta name="description" content="Generated by the power of digIT 😈" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <QueueList />
        <div className={styles.content}>
          <Header />
        </div>
      </main>
      <PlayBar />
    </>
  );
}
